### ISSUE TITLE
Missing an occurrence of `@` in `XObjectImage.tsv`

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/arlington-pdf-model#11]
Not sure whether this is a bug, but it seems at least inconsistent:

In `XObjectImage.tsv`, `BitsPerComponent`, `Required` field, there's a usage of `ImageMask` but without `@` prefix.

This is discovered when trying to read and parse the tsv data...

**Comment by petervwyatt** [comment]
Well spotted! Thank you.
Fixed with latest commit along with some other incorrect versioning that gave (correct) validation warnings
