### ISSUE TITLE
Extend Arlington extension to document OpenOffice and LibreOffice custom trailer keys

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/arlington-pdf-model#111]
In file trailer and XRefStream:

* `/AdditionalStreams [/application#2Fvnd#2Eoasis#2Eopendocument#2Etext 6 0 R]` (ODT document) - an array of pairs of (MIME as a name + indirect references to streams)
 
* `/DocChecksum /DocChecksum /C2ABA76E903B138C5EC5DE44D0AE2A77` (MD5 as a name)

See https://git.libreoffice.org/core/+/refs/heads/master/vcl/source/gdi/pdfwriter_impl.cxx

**Comment by crlf0710** [comment]
Are these correct uses of first-class names?
