### ISSUE TITLE
signature not displayed in fully-compliant document

### ISSUE THREAD

**Issue by ousia** [pdf-association/arlington-pdf-model#119]
> [This report comes from veraPDF/veraPDF-arlington-tools#2.]

The [attached document](https://github.com/user-attachments/files/15775367/a.pdf) contains a digital signature.[^signature]

For some reason unknown to me, Acrobat Reader doesn’t display the signature pane or any signature icon.

I’m afraid I cannot provide an screenshot (on a Linux machine right now), but this would be similar to having document outlines or bookmarks and not being displayed by the PDF viewer.

Using the `arlington-pdf-model-checker-gui-1.27.16` (latest version known to me), I get perfect validation of this document: no deviation found.

Of course, I do not intend to report a reader issue (I know this wouldn’t be the repository for that), but I wonder whether there is a missing requirement for this document not added as a rule in the Arlington PDF model. 

Many thanks for your help.

[^signature]: As reported from MuPDF-1.24.1:

    ``` bash
    $ mutool sign -v a.pdf 
    Verifying signature 3:
    Distinguished name: cn=John Doe, o=No Brainer, ou=, email=, c=XX
      Certificate error: Self-signed certificate.
      The document is unchanged since signing.
    ```
    Also poppler-utils-24.02 report:

    ``` bash$ pdfsig a.pdf 
    Digital Signature Info of: a.pdf
    Signature #1:
      - Signature Field Name: signature
      - Signer Certificate Common Name: John Doe
      - Signer full Distinguished Name: CN=John Doe,O=No Brainer,L=Default City,C=XX
      - Signing Time: Jun 09 2024 11:50:53
      - Signing Hash Algorithm: SHA-256
      - Signature Type: adbe.pkcs7.detached
      - Signed Ranges: [0 - 6426], [10524 - 10909]
      - Total document signed
      - Signature Validation: Signature is Valid.
      - Certificate Validation: Certificate issuer isn't Trusted.
    ```

    Only to show that the signature is contained in the document.

**Comment by petervwyatt** [comment]
This is a vendor-specific issue with their implementation - please report to them. I do note that Acrobat wants to save the file after opening which indicates it thinks something is malformed - maybe if you examined a repaired file you might be able to work out what it doesn't like. Maybe there is an optional key it thinks is required...

I tested across multiple other popular viewing implementations and they all see the signature and can successfully validate the PDF as not being modified. Arlington reports no issues with the PDF from a latest specification (incl. errata) point-of-view (Arlington does NOT model signature validation (e.g. values of ByteRange) or tamper-detection as those are implementation details).

Closing.

**Comment by mkl-public** [comment]
While this is not the Acrobat support forum, some observations which may explain the Acrobat behavior:

### Acrobat wants to save the file upon closing

> I do note that Acrobat wants to save the file after opening which indicates it thinks something is malformed

While that often is the case and may be here, too, there is yet another reason for this in the file at hand: In its **AcroForm** dictionary
```<< /Fields 19 0 R /NeedAppearances true >>```
it announces that appearances for its widgets need to be created. And if the file asks for changes, Acrobat applies changes and wants to save.

`/NeedAppearances true` in a signed PDF in general is not a good idea...

### Acrobat only showing signature UI if `SigFlags` are given

Indeed, one can wonder why Acrobat not simply looks at the form fields to determine the presence of signature fields and signatures. On the other hand, the signature flags are specified to signal just that.

As there may be signatures which are not in fields (usage rights signatures in particular), looking at the signature flags may even be more relevant than scanning the form fields...

Essentially this is a matter of implementation choice.
