### ISSUE TITLE
Data inconsistency between TSV version and XML version

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/arlington-pdf-model#2]
Hello, i'm trying to write a small program to read the TSV version data files. There're quite a few semicolons within the data so i started investigating into how to interpret them. Then i noticed that there is data inconsistency, so let me create an issue here.

In the TSV file `ActionThread.tsv`,
```text
D	dictionary;integer;string-text	1.1		TRUE	[TRUE];[FALSE];[FALSE]	FALSE		[];[fn:Eval(@D>=0 && @D<fn:ArrayLength(Catalog::Threads))];[]		[Thread];[];[]	
```

the [TRUE];[FALSE];[FALSE] corresponds to the IndirectReference field, looking at ISO 32000-2:2020, there is indeed text that specifies that if `D` field value is a dictionary, it shall be a indirect reference.

But in `pdf_grammar2.0.xml`, `<OBJECT id="ActionThread" object_number="034">`,
D field is this:
```text
      <ENTRY>
         <NAME>D</NAME>
         <VALUES>
            <VALUE type="dictionary">fn:SinceVersion(1.1,Thread)</VALUE>
            <VALUE type="integer"/>
            <VALUE type="string-text"/>
         </VALUES>
         <REQUIRED>true</REQUIRED>
         <INDIRECT_REFERENCE>false</INDIRECT_REFERENCE>
         <INHERITABLE>false</INHERITABLE>
         <INTRODUCED>1.1</INTRODUCED>
         <DEPRECATED/>
         <SPECIAL_CASE/>
      </ENTRY>
```
So it seems the "an indirect reference to a thread dictionary" information is missing.

**Comment by petervwyatt** [comment]
Yes - sorry about that. 

The XML data is quite out of date, as the focus has been on expanding the expressiveness of the predicates (declarative functions). I'll look at getting everything "re-aligned" very soon...

**Comment by petervwyatt** [comment]
This is now corrected on the branch testgrammar-rewrite-pdfium which has other very significant changes - including to the overall Arlington grammar, the Arlington data, and less so to the XML schema. The Java has also been optimized and heavily commented (JavaDoc) as well as dedicated README.md.

I will merge this branch to main very soon.
