### ISSUE TITLE
Undefined predicates

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#22]
`Target` (ISO32K2:2020 table 205) uses:

* fn:NumberOfPages()
* fn:PageProperty(pagenumber,key)

Neither of these are defined in the list of [Predicates](https://github.com/pdf-association/arlington-pdf-model/blob/master/INTERNAL_GRAMMAR.md#predicates-declarative-functions)

**Comment by petervwyatt** [comment]
Thanks. This is fixed on the "extensions" branch - I suggest you switch to that to see if you can find any more of my mistakes as I'd like to pull it across to master soon.

**Comment by petervwyatt** [comment]
Fixed on "Extensions" bramch

**Comment by faceless2** [comment]
Just a heads up, I can't find either of these in the extensions  branch: I'm checking

https://github.com/pdf-association/arlington-pdf-model/blob/extensions/INTERNAL_GRAMMAR.md

**Comment by petervwyatt** [comment]
Fixed for real this time.
Note also a minor fixup in `Target.tsv` too
