### ISSUE TITLE
ActionHide T field is incorrect

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#23]
In`ActionHide` the `T` value refers to a list of actions - looks like a copy-past errors from the `Next` field. It should be

```
• An indirect reference to an annotation dictionary
• A text string giving the fully qualified field name of an interactive form field whose associated widget annotation or annotations are to be affected (see 12.7.4.2, "Field names")
• An array of such dictionaries or text strings
```

**Comment by petervwyatt** [comment]
Thanks! Great find. Resolved on "Extensions" branch (data yet to be propagated to PDF version data models).
Also added a new predicate to test for valid partial Field Names - see INTERNAL_GRAMMAR.md on branch
