### ISSUE TITLE
Wildcard matches

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#25]
The `AnnotStamp` type has this for `Name` possible values

```
[Approved,Experimental,NotApproved,AsIs,Expired,NotForPublicRelease,Confidential,Final,Sold,Departmental,ForComment,TopSecret,Draft,ForPublicRelease] 
```

the spec says (my emphasis added)

> The name of an icon that shall be used in displaying the annotation. PDF writers should include this entry and PDF readers should provide predefined icon appearances for at least the following standard names:
Approved, Experimental, NotApproved, AsIs, Expired, NotForPublicRelease, Confidential, Final, Sold, Departmental, ForComment, TopSecret, Draft, ForPublicRelease
**Additional names may be supported as well**. Default value: Draft.

So I think this one needs a wildcard at the end of the list - values other than this are pretty common, any custom stamp in Acrobat will have a value not in this list.

----

Same issue with the `ActionNamed` type, where the `N` field is limited to `[NextPage,PrevPage,FirstPage,LastPage]`. This is the minimum list for compat, but named beyond this list shouldn't be invalid.

> "Table 215 — Named actions" lists several named actions (PDF 1.2) that interactive PDF processors shall support; further names may be added in the future.

> NOTE Interactive PDF processors may support additional, nonstandard named actions, but any document using them is not portable.

> If the PDF processor encounters a named action that is inappropriate for a viewing platform, or if the viewer does not recognise the name, it shall take no action.

----

And just in case you're of the opinion that there's no change here because the spec doesn't _explicitly_ say "or wildcard" in the table, here's my counter argument:

I still think there needs to be a distinction between these "invalid because not listed, although items not on the list are permitted" and "properly invalid", such as when you set /Type/Foo on a page. Would you consider something like `fn:IsExtension(general,*)` in this case to show that other values are allowed?

**Comment by petervwyatt** [comment]
Within SafeDocs I had previously considered this as there are a number of places within the PDF spec that explicitly mention that additional arbitrary values are allowed in addition to some pre-defined set (e.g. annots). This should(!) mean that all implementations support the full minimum set, but some may then be more flexible than others in accepting the additional "outliers" - and exactly what they should be doing is outside the scope of the PDF spec. And this is different _semantically_ to where an arbitrary 'thing' can get used (such as a resource name).

**Comment by petervwyatt** [comment]
So if I were to expand the data model, I think I'd want to use a different syntax to distinguish these cases from the other current uses of "wildcard" as there is this subtle semantic differences that I'd like to encode into the data model. So maybe use a different symbol such as "$" or "#" (makes my brute force parsing and CLI grepping easier than supplementing "*"). Comments?

**Comment by faceless2** [comment]
Yes, I figured you'd have considered this. So long as the concept is in there I don't mind, being a java bod I have a preference for clarity over brevity so would go with a function, but it's your project. Although I'd steer clear of "#" for obvious name-related reasons.

For contrast, so we have a record of it here: the only place `*` is currently used is in the `OptContentCreatorInfo` tables (table 100 in 32K) where Subtype is defined as `[Artwork,Technical,*]`

> **Subtype** - A name defining the type of content controlled by the group. Suggested values include but shall not be limited to _Artwork_, for graphic-design or publishing applications, and _Technical_, for technical designs such as building plans or schematics.

So I see the semantic difference you're trying to capture - the difference between "anything" and "here's a list which you may deviate from if necessary".

**Comment by petervwyatt** [comment]
And I also notice that I contradict myself - see `OptContentCreatorInfo.tsv` where PossibleValues is `[Artwork,Technical,*]`

**Comment by petervwyatt** [comment]
Been thinking about this some more... I know inside ISO and across TC130 and TC171 there have been various discussions as this also impacts what PDF 2.0 TS extensions might theoretically be allowed to change or extend (but not break things!) and the subtly of various wording choices when describing possible values ("shall be", "shall include", "are", "is", etc). Lots of historic wording here!

PDF is an extensible language so anybody can extend anything so long as they follow the "rules" - a 2nd class name can theoretically extend ANY set of values anywhere (cf. AFRelationship in Table 43 where this is explicitly called out). But that doesn't account for non-name values such as integers or numeric values, strings, etc. Or even if the type of an entry is extended. The new PDF TS crypto extensions might be considered to "break" some existing requirement statements if we get technical about certain wording choices...

So I am biasing to REMOVING this for values and having Arlington only model the explicit values described in 32K, since everything is always extensible and the subtly of wording is not intentional. Comments?

**Comment by faceless2** [comment]
True enough, it is extensible. But the spec makes it clear where non-specified values are to be _expected_ - so if the model represents the spec, I think it's appropriate for the model to encode that information.

More practically, the distinction definitely matters If you go with `[Artwork,Technical]` and someone uses another value, that's OK - a warning at best. If you go with `[Catalog]` and someone uses another value, it's not OK. 

We're anticipating adding the Arlington model to our validation process, and eventually using it as the basis for repair - if the document Catalog has the wrong Type, we'll fix it. But if we don't make the distinction between "extensions possible" and "no extensions possible" we won't even get off the ground with this, there will be too many false positives.

Personally I like `*`, it's concise and grep-able. If it were me I'd add it on to the list wherever the spec explicitly states that "other values are possible" - Artwork|Technical, named actions, stamp names, AFRelationship etc.

**Comment by petervwyatt** [comment]
I do 100% agree `*` is a far nicer and user-friendly syntax. 

I have now stripped out all non-essential `*` that were lurking in the Notes field so now a grep only returns `*` wildcards that reference a Key (field 1) and multiplication symbols used as part of predicates.

**Comment by petervwyatt** [comment]
Done - but not AFRelationship because that explicitly says it needs to be a 2nd class name which is no different to any other key value.
