### ISSUE TITLE
DeviceN color introduced in 1.3, not 1.6

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#26]
The `ColorSpaceMap` key has

```
fn:SinceVersion(1.6,DeviceNColorSpace)
```
DeviceN was introduced in 1.3 (32K2 8.6.6.5)- it was NChannel that was added in 1.6.

This will knock in into a few other tables, not least `DeviceNColorSpace`

**Comment by petervwyatt** [comment]
Thanks! Fixed on "extensions" branch
