### ISSUE TITLE
FieldCh V may be an array.

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#31]
This one is buried in the text - final paragraph just before 12.7.5.5, but for choice fields V may be an array of text-strings, as well as a text-string.

A possible contender for an item that should be promoted from the explanatory text to the table above it (Table 234)

(should this also apply to DV? It currently doesn't)

**Comment by petervwyatt** [comment]
Great find! Fixed on the "Extensions" branch.

**Comment by petervwyatt** [comment]
On further review of more Field related text, I'm thinking that Arlington should specialize `FieldBtn` to `FieldBtnPush`, `FieldBtnCheckBox` and `FieldBtnRadio` so that more specific rules can be captured. What do you think?

**Comment by faceless2** [comment]
Yes, I wondered about that too.

There aren't really many hard differences between them. I'm particularly  thinking of PDF/A here, which has this text:

> For all annotation dictionaries containing an AP key, the appearance dictionary that it defines as its value shall contain only the N key. If an annotation dictionary’s Subtype key has a value of Widget and its FT key has a value of Btn, the value of the N key shall be an appearance subdictionary; otherwise the value of the N key shall be an appearance stream.

Although it's normal for a push button to have `/AP<</N 1 0 R>>`, this forces us to do `/AS/foo/AP<</N<</foo 1 0 R>>>>` for PDF/A.  Which is the normal approach for radio-buttons/check-boxes, and odd-but-valid for push-buttons.

My point is the way the two are used is fairly interchangeable. So no firm opinion, but so far I haven't hit any issue where this would help.

**Comment by petervwyatt** [comment]
I think I will go ahead and make the specialized Field definitions so I can capture the subtly different rules in a more targeted fashion. e.g. push buttons "shall not use" **V** and **DV**; the type(s) for **V**/**DV** keys; the additional flag for radio buttons, the relationship between **V** and **AS**; etc. I feel there are enough reasons...

PS. I interpret "shall not use" as a processor requirement equivalent to "ignore", not a file format requirement that says the keys cannot exist.

**Comment by petervwyatt** [comment]
Fixed

**Comment by faceless2** [comment]
You have
```
Radio:  [fn:Eval(fn:BitsClear(4,14) && fn:BitSet(16)   && fn:BitsClear(17,25) && fn:BitsClear(27,32))]
Check:  [fn:Eval(fn:BitsClear(4,14) && fn:BitClear(16) && fn:BitsClear(18,25) && fn:BitsClear(27,32))]
Push:   [fn:Eval(fn:BitsClear(4,14) &&                    fn:BitsClear(18,25) && fn:BitsClear(27,32))] 
```
But a push button _must_ have bit 17 set - that's not being tested for. Without it Checkboxes are indistinguishable from push-buttons

**Comment by petervwyatt** [comment]
Thanks.
```
$ tsv-pretty FieldBtn*.tsv | grep Bits
Ff      bitmask                      1.2                FALSE     FALSE              TRUE                                       [fn:Eval(fn:BitsClear(4,14) && fn:BitsClear(16,25) && fn:BitsClear(27,32))]         Table 227 and Table 229
Ff      bitmask                      1.2                FALSE     FALSE              TRUE                                       [fn:Eval(fn:BitsClear(4,14) && fn:BitClear(16) && fn:BitSet(17) && fn:BitsClear(18,25) && fn:BitsClear(27,32))]  Table 227 and Table 229
Ff      bitmask                      1.2                FALSE     FALSE              TRUE                                       [fn:Eval(fn:BitsClear(4,14) && fn:BitSet(16) && fn:BitsClear(17,25) && fn:BitsClear(27,32))]  Table 227 and Table 229
```
