### ISSUE TITLE
FunctionTypeN tests

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#32]
FunctionType0 makes a special-case test on the `Size` and `Decode` keys, but they are against another key which is optional, so the test will often be skipped. It can be rephrased against a required key. Proposed changes:

```
Size      [fn:Eval(fn:ArrayLength(Domain)==(2 * fn:ArrayLength(Size)))]
Decode    [fn:Eval(fn:ArrayLength(Decode)==fn:ArrayLength(Range))]
```

**Comment by petervwyatt** [comment]
Nice. Arguably ISO 32K would also be easier to understand if it was worded this way too!
