### ISSUE TITLE
fn:IsPresent() takes two args, grammar description only describes one

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#34]
`fn:IsPresent(VA,0)` is in one of the models

https://github.com/pdf-association/arlington-pdf-model/blob/extensions/INTERNAL_GRAMMAR.md

EDIT - also, it appears if the second value is specified the return is not true or false, it is _value_ or _undefined_. Should note this.

**Comment by petervwyatt** [comment]
I took the other way out and removed this anomaly. 
Expressing complex default values (ie. that involve other dicts or arrays) aren't really supported yet so it would be better to wait and do everything once consistently.
