### ISSUE TITLE
AnnotLine LLE test incorrect

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#35]
The `LLE` field in `AnnotLine` has

```
 [fn:Eval(@LLE>0)]
```

this should be >= 0 - particularly because the default is 0! It's non-negative.

>  A non-negative number that shall represents the length of leader line extensions that extend from the line proper 180 degrees from the leader lines, as shown in "Figure 80 — Leader lines".
Default value: 0 (no leader line extensions).

**Comment by petervwyatt** [comment]
Thanks. I suspect you may also find more such things...

See also [Errata #191](https://github.com/pdf-association/pdf-issues/issues/191) and Issue #17 here.
