### ISSUE TITLE
java.lang.NullPointerException: Cannot read the array length because "<local4>" is null?

### ISSUE THREAD

**Issue by Albretch** [pdf-association/arlington-pdf-model#37]
// __ java.lang.NullPointerException: Cannot read the array length because "<local4>" is null

$ which java
.../graalvm-ce-java17-22.2.0/bin/java

$ java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

$ which javac
.../graalvm-ce-java17-22.2.0/bin/javac

$ javac -version
javac 17.0.4

$ ls -l ./gcxml.jar
-rwxrwxrwx 1 root root 52922 Oct  8 04:24 ./gcxml.jar

$ file ./gcxml.jar
./gcxml.jar: Java archive data (JAR)

$ sha256sum --binary ./gcxml.jar
746a6a37d5bd80929a78522a079b964a0879305714f0223b7f9b316a97411bb7 *./gcxml.jar

$ java -jar ./gcxml.jar -xml
gcxml 0.5.0
java.lang.NullPointerException: Cannot read the array length because "<local4>" is null
GENERAL:
        -version                print version information (current: 0.5.0)
        -help                   show list of available commands
CONVERSIONS:
        -all                    convert latest TSV to XML and TSV sub-versions for each specific PDF version
        -xml <version>          convert TSV to XML for specified PDF version (or all if no version is specified)
        -tsv                    create TSV files for each PDF version
QUERIES:
        -sin <version | -all>   return all keys introduced in ("since") a specified PDF version (or all)
        -dep <version | -all>   return all keys deprecated in a specified PDF version (or all)
        -kc                     return every key name and their occurrence counts for each version of PDF
        -po key<,key1,...>      return list of potential objects based on a set of given keys for each version of PDF
        -sc                     list special cases for every PDF version
        -so                     return objects that are not defined to have key Type, or where the Type key is specified as optional
Note: output might be too long to display in terminal, so it is recommended to redirect the output to file (eg <command> > report.txt)
$

**Comment by petervwyatt** [comment]
The documentation for the gcxml utility is poor, but you need to run it from the arlington-pdf-model folder. See https://github.com/pdf-association/arlington-pdf-model#gcxml-java where it says:
> The Java gcxml.jar file must be run in this top-level folder (such that `./tsv/` and `./xml/` are both sub-folders).

So CLI needs to be:
```bash
java -jar ./gcxml/dist/gcxml.jar -xml
```

**Comment by petervwyatt** [comment]
I should also add that gcxml has not been fully maintained since the majority of users are using the master TSV data or JSON/Jupyter data models. Some of its features may no longer work with the latest round of changes to the internal grammar.

gcxml is currently only being used to convert the TSV data to an XML equivalent, but the XML processing has likely rotted.
