### ISSUE TITLE
Catalog Extensions, whole tree must be direct

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#41]
This is from the discussion on the PDF TWG mailing list.

The end of paragraph 7.12.1, immediately before Table 48 in ISO32000:2020 we have this text:

> The extensions dictionary, all developer extensions dictionaries, as well as their entries, shall be direct objects (i.e., this information shall be nested directly within the catalog dictionary with no indirect objects used).

This is partially captured in the model (`Extensions.tsv` and `DevExtensions.tsv` are fine) but not completely - I think you also need `fn:MustBeDirect()` on the following objects

* `Catalog.tsv`, `Extension` key
* `ArrayOfDevExtensions.tsv`, `*` key

**Comment by MatthiasValvekens** [comment]
See also pdf-association/pdf-issues#242, which is probably the reason why this wasn't noticed earlier :).

**Comment by petervwyatt** [comment]
Fixed in `tsv/latest`. Not yet propagated to XML, TSV versions, etc.
