### ISSUE TITLE
DA in signature field dictionary: really required?

### ISSUE THREAD

**Issue by a20dev** [pdf-association/arlington-pdf-model#45]
According to FieldSig.tsv (all versions), the DA entry is required for signature fields. However, I cannot find wording to that effect in ISO 32000-2:2020.

12.7.5.5 (Signature Fields) says "The field dictionary representing a signature field may contain the additional entries listed in Table 235 [...]  as well as the standard entries described in Table 226 [...l]". DA is not in those tables. (Existing practice is that DA is optional for signature fields.)

DA is required only for fields containing variable text. ISO 32000-2:2020 does not specify that signature fields are fields containing variable text.

Note that a signature field (or rather the appearance of its widget annotation) does not have to contain text once it is signed, it may also contain just an image.

**Comment by petervwyatt** [comment]
See also Issue #28.

**Comment by a20dev** [comment]
About #28: the only annotations that have a DA entry are freetext annotations. In a  signature field dictionary merged with its widget annotation dictionary, the DA entry belongs to the field dictionary.

**Comment by petervwyatt** [comment]
Resolved in `./tsv/latest` but data model not propagated to the PDF version specific file sets.
Thanks for reporting!

The "_required if field contains variable text_" is not yet encoded into the data model - that is part of Issue #28. But I added as a comment (right-most "Note" field) to the DA key in `FieldSig.tsv`.
