### ISSUE TITLE
-o option no longer works like it used to in TestGrammar

### ISSUE THREAD

**Issue by tballison** [pdf-association/arlington-pdf-model#48]
This could be user error.  I tried to update the docker file for the Tika wrapper and was not getting the output I expected.  So, I tried building from scratch outside of Docker.

On Ubuntu, I cloned main and followed the build directions successfully.

I then tried `./bin/linux/TestGrammar_d --no-color --clobber -t ../tsv/latest -o ~/Desktop/tmp-arlington.txt -p ~/Downloads/MS-EMF-210625.pdf`

The application reported:
```
Processing "/home/tallison/Downloads/MS-EMF-210625.pdf" to "/home/tallison/Desktop/tmp-arlington.txt/MS-EMF-210625.txt" 
DONE - 1 files processed
```

It did not create an output directory and wrote no file.  It did take a while to do the processing...it was clearly running.

When I created an output directory and ran `./bin/linux/TestGrammar_d --no-color -t ../tsv/latest -o ~/Desktop/output -p ~/Downloads/MS-EMF-210625.pdf`

The application reported:
```
Processing "/home/tallison/Downloads/MS-EMF-210625.pdf" to "/home/tallison/Desktop/output/MS-EMF-210625.txt"
DONE - 1 files processed
```

And it did write the file it said it would there.  I got the same behavior when I added `--clobber`.

I think the behavior with clobber used to be that it would write stdout to the file specified by `-o`, not try to write a file named after the input file in a directory specified by -o?

**Comment by petervwyatt** [comment]
Sorry about that! I had a different request that I attempted to support and broke things...

Here is the latest behaviour fully documented:

`--clobber` will overwrite output files if files of the same name are encountered. The default behaviour is to **avoid** overwriting output files by appending underscores (`_`) to the filename (before the extension) until there is no filename collision. 

| | `--out` option is a file | `--out` option is a folder | no `--out` specified |
| --- | --- | --- | --- |
| `--pdf` option is a file: | output of single PDF is written to the specified file. _**Always clobbers!**_ | output written to file named after the PDF file with extension changed to `.txt` or `.ansi` depending on `--no-color` option. `--clobber` option will be obeyed | output of single PDF to stdout. |
| `--pdf` option is folder: | all outout written to the single specified file. `--clobber` option will be obeyed. | output written to individual files, each named after the PDF file with the extension is changed to `.txt` or `.ansi` depending on `--no-color` option. `--clobber` option will be obeyed. | output from all PDFs to stdout. |

Note that the `--out` option will **not** create any folders!
