### ISSUE TITLE
StructureAttributesDict.tsv Placement - no Inline value?

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#70]
An odd one that we've found as part of our PDF/UA tests

The `Placement` key has `[Block,Before,Start,End,fn:BeforeVersion(2.0,Inline)]` as values -  I don't know why Inline has that restriction? It's defined as far back as PDF 1.4 all the way through to 32K-2.

**Comment by petervwyatt** [comment]
I think this is a hangover from when Struct Attributes were defined differently. I agree it is wrong.
