### ISSUE TITLE
Invalid special case for Start in MovieActivation

### ISSUE THREAD

**Issue by MaximPlusov** [pdf-association/arlington-pdf-model#72]
Special case for Start in MovieActivation is currently `fn:Eval(@Start>0)` while it should be `fn:Eval(@Start>=0)`

ISO 32000-2, table 307: `The starting time shall be nominally a non-negative 64-bit integer`

**Comment by petervwyatt** [comment]
Proper validation should have also noted that the default value of 0 was therefore also invalid!
