### ISSUE TITLE
Named Destinations should include GoTo Actions

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/arlington-pdf-model#75]
Clause 12.3.2.4 Named destinations should fully allow GoTo Actions as well as the "minified" `DestDict`.
`ActionGoTo`, `ActionGoToR` and `ActionGotoE` should all be added to `DestMap` and `Name`.

See also https://github.com/pdf-association/pdf-issues/issues/288.

**Comment by MaximPlusov** [comment]
ActionGoToE should be wrapped in fn:SinceVersion(1.6,ActionGoToE)
